apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: coldchain
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 443071119316.dkr.ecr.us-west-2.amazonaws.com/coldchain-redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --maxmemory
            - "200mb"
            - --maxmemory-policy
            - allkeys-lru
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi